
title: Statetty
email: info@Statetty.com
short: "La navaja suiza del agente inmobiliario"
description: "Statetty es la plataforma todo-en-uno para agentes inmobiliarios. ✅ Automatiza la búsqueda de inmuebles, monitoriza oportunidades en WhatsApp y te conecta con colegas. Ahorra tiempo, cierra más negocios y potencia tu productividad."
keywords: "agente inmobiliario, software inmobiliario, herramientas para inmobiliarias, plataforma inmobiliaria, automatización inmobiliaria, buscar inmuebles automático, chatbot inmobiliario, inteligencia artificial inmobiliaria, ahorrar tiempo agente inmobiliario, monitorear WhatsApp inmobiliario, alertas propiedades tiempo real, centralizar datos inmobiliarios, analisis comparativo de mercado automático, conectar agentes inmobiliarios, cocierres inmobiliarios, statetty bot, statetty telegram, precios statetty, tutorial statetty, software inmobiliario Santa Cruz, herramientas inmobiliarias Bolivia, buscar propiedades Santa Cruz, inmobiliarias Santa Cruz de la Sierra, plataforma inmobiliaria boliviana, cursos agentes inmobiliarios Santa Cruz, demo herramienta inmobiliaria, prueba gratis plataforma inmobiliaria, planes statetty, reducir tiempo búsqueda inmuebles, aumentar productividad agente inmobiliario, encontrar oportunidades negocio ocultas, no perder leads WhatsApp, centralizar información inmobiliaria, vender más inmuebles, departamento, casa, terreno, bienes raíces, anticrético, venta, alquiler, gestión de prospectos, API inmobiliaria, educación inmobiliaria, talleres para agentes inmobiliarios, redes sociales inmobiliarias, mercado inmobiliario Bolivia"

siteImage: "statetty.png"

social:
  twitter:    "statetty"
  facebook:   "statetty"
  instagram:  "statetty"
  tiktok:     "statetty"
  whatsapp:   "https://wa.me/59178447518"
  telegram:   "https://t.me/statettybot"
  github:     false
  linkedin:   false
  flickr:     false
  youtube:    statetty
  googleplus: false
  pinterest:  false

baseurl:      "" 
url:          "https://statetty.com" 
timezone:     "America/La_Paz"
locale:       "es_ES"
encoding:     "utf-8"
imageFolder:  "/assets/images/"
ICBM:         "-17.7833152;-63.1821236"
region:       "BO-S"
placename:    "Santa Cruz de la Sierra"

# About/contact
author:
  name:             Alejandro Sosa Briceño
  url:              asosab.github.io
  github:           asosab
  google_analytics: UA-84695-6
  disqus:           codigo-nuestro
  linkedin:         alejandrososa
  twitter:          asosab
  facebook:         asosab
  email:            alejandro.sosa@statetty.com
  region:           BO-S
  placename:        Santa Cruz de la Sierra
  ICBM:             "-17.7833152;-63.1821236"
  flickr:           alejandrososa
  instagram:        alejandrososab
  youtube:          asosab
  googleplus:       AlejandroSosaBriceño
  pinterest:        asosab    


# Build settings
markdown:     "kramdown"
highlighter:  "rouge"
kramdown:
  input:                  "GFM"
  hard_wrap:              false
  syntax_highlighter_opts:
    format_style:         'div'
    css_class:            'highlight'
    span:
      line_numbers:       false
    block:
      line_numbers:       true

permalink: /:title/

webrick:
  headers:
    Strict-Transport-Security: max-age=2592000

# gems
plugins:
  - rouge
