# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Statetty
email: info@Statetty.com
description: "Statetty ofrece una plataforma tecnológica que centraliza datos de inmuebles y proporciona alertas personalizadas en tiempo real. Además, brinda talleres prácticos para automatizar respuestas, gestionar prospectos y usar inteligencia artificial, mejorando la eficiencia y efectividad de los agentes inmobiliarios."
keywords: "inmobiliarias, agentes inmobiliarios, búsqueda de inmuebles, tecnología inmobiliaria, Telegram, Statetty, Santa Cruz, Bolivia, educación inmobiliaria, talleres inmobiliarios, inteligencia artificial inmobiliaria, alertas inmobiliarias, mercado inmobiliario, propiedades en venta, propiedades en alquiler, redes sociales inmobiliarias, automatización inmobiliaria, gestión de prospectos, API inmobiliaria, chatbot inmobiliario"

social:
  twitter_username: statetty
  facebook_username: statetty
  instagram_username: statetty
  tiktok_username: statetty
  whatsapp: "https://wa.me/59178447518"
  telegram: "https://t.me/statettybot"

baseurl: "" 
url: "https://statetty.com" 
timezone:       America/La_Paz
locale:         es_ES
encoding:       utf-8
imageFolder:    "/imagen/"

# About/contact
author: Alejandro Sosa Briceño         


# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    format_style: 'div'
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

permalink: /:title/

webrick:
  headers:
    Strict-Transport-Security: max-age=2592000

# gems
plugins:
  - jekyll-gist
  - rouge

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
