
title: Statetty
email: info@Statetty.com
description: "Statetty ofrece una plataforma tecnológica que centraliza datos de inmuebles y proporciona alertas personalizadas en tiempo real. Además, brinda talleres prácticos para automatizar respuestas, gestionar prospectos y usar inteligencia artificial, mejorando la eficiencia y efectividad de los agentes inmobiliarios."
keywords: "inmobiliarias, agentes inmobiliarios, búsqueda de inmuebles, tecnología inmobiliaria, Telegram, Statetty, Santa Cruz, Bolivia, educación inmobiliaria, talleres inmobiliarios, inteligencia artificial inmobiliaria, alertas inmobiliarias, mercado inmobiliario, propiedades en venta, propiedades en alquiler, redes sociales inmobiliarias, automatización inmobiliaria, gestión de prospectos, API inmobiliaria, chatbot inmobiliario"

social:
  twitter_username: statetty
  facebook_username: statetty
  instagram_username: statetty
  tiktok_username: statetty
  whatsapp: "https://wa.me/59178447518"
  telegram: "https://t.me/statettybot"

baseurl: "" 
url: "https://statetty.com" 
timezone:       America/La_Paz
locale:         es_ES
encoding:       utf-8
imageFolder:    "/imagen/"

# About/contact
author: Alejandro Sosa Briceño         


# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    format_style: 'div'
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

permalink: /:title/

webrick:
  headers:
    Strict-Transport-Security: max-age=2592000



remote_theme: pages-themes/architect@v0.2.0

# gems
plugins:
  - jekyll-feed
  - rouge
  - jekyll-remote-theme
